import api, { route } from '@forge/api';
import { isValidIssueKey } from '../utils/validators.js';

export const autoFixTicket = async (issueKey, contentInput) => {
    let improvedContent = contentInput;
    console.log(`[Auto-Fix] Processing ${issueKey}`);

    if (!isValidIssueKey(issueKey)) {
        throw new Error(`Invalid Issue Key format: "${issueKey}". Expected format like "KAN-123".`);
    }

    if (!improvedContent) {
        // Fallback for Custom UI invocation where LLM isn't pre-generating content
        console.warn("Missing improvedContent. Generating automated improvement...");
        improvedContent = `**Issue Analysis:**
1.  **Ambiguity Detected**: The summary is vague.
2.  **Missing Context**: No environment details provided.

**Suggested Improvements:**
*   **Steps to Reproduce**:
    1.  Navigate to the affected page.
    2.  Perform action X.
    3.  Observe error Y.
*   **Expected Behavior**: System should respond within 200ms.
*   **Actual Behavior**: System times out.

*(Automated by Rovo Agent)*`;
    }

    try {
        const res = await api.asApp().requestJira(route`/rest/api/3/issue/${issueKey}`);
        if (!res.ok) {
            const err = await res.text();
            if (res.status === 404) throw new Error(`Ticket ${issueKey} not found.`);
            throw new Error(`Failed to fetch issue: ${res.status} - ${err}`);
        }
        const issue = await res.json();

        // Business Logic: Don't fix closed tickets
        const status = issue.fields.status?.name;
        if (status === 'Done' || status === 'Closed') {
            throw new Error(`Ticket is already ${status}. No action needed.`);
        }

        // Construct ADF from the AI's input
        // Using a safe default structure to ensure valid ADF
        const descriptionADF = {
            type: "doc",
            version: 1,
            content: [
                {
                    type: "paragraph",
                    content: [{ type: "text", text: "✅ Improved by Rovo Orchestrator" }]
                },
                {
                    type: "heading",
                    attrs: { level: 3 },
                    content: [{ type: "text", text: "📋 Acceptance Criteria & Steps" }]
                },
                {
                    type: "paragraph",
                    content: [{ type: "text", text: improvedContent }]
                },
                {
                    type: "paragraph",
                    content: [{ type: "text", text: "(Generated by Rovo AI)" }]
                }
            ]
        };

        const updateRes = await api.asApp().requestJira(route`/rest/api/3/issue/${issueKey}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                fields: { description: descriptionADF }
            })
        });

        if (!updateRes.ok) {
            throw new Error(`Update failed: ${updateRes.status}`);
        }

        return { success: true, message: `Ticket ${issueKey} updated with improved content.` };
    } catch (e) {
        console.error("Auto-Fix failed:", e);
        throw e;
    }
};
