import api, { route } from '@forge/api';
import { addComment } from '../services/jira.js';

export const chaosMonkey = async (projectKey) => {
    console.log(`[Chaos Monkey] Unleashing chaos on ${projectKey || 'KAN'}...`);

    const scenarios = [
        "🔥 Database CPU at 99%",
        "🚨 Payment Gateway Timeout (504)",
        "⚠️ Frontend Assets 404",
        "💀 Memory Leak in Worker Node",
        "🛑 API Rate Limit Breached"
    ];

    // Pick 3 random scenarios
    const selected = scenarios.sort(() => 0.5 - Math.random()).slice(0, 3);
    const createdKeys = [];

    try {
        for (const summary of selected) {
            const body = {
                fields: {
                    project: { key: projectKey || 'KAN' },
                    summary: `[CHAOS] ${summary}`,
                    issuetype: { name: "Task" }, // Keep "Task" as it is standard
                    description: {
                        type: "doc",
                        version: 1,
                        content: [{ type: "paragraph", content: [{ type: "text", text: "Auto-generated by Chaos Monkey 🐵. Investigate immediately!" }] }]
                    }
                    // Removing Priority to fallback to default
                }
            };

            // Use asUser() to ensure permissions match the logged-in admin
            const res = await api.asUser().requestJira(route`/rest/api/3/issue`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(body)
            });

            if (res.status === 201) {
                const data = await res.json();
                createdKeys.push(data.key);
                // Add comment
                await addComment(data.key, '🔥 Chaos Monkey struck here!');
            }
        }
        return { success: true, message: `⚠️ Chaos Unleashed! Created: ${createdKeys.join(', ')}` };
    } catch (e) {
        console.error("Chaos Monkey failed:", e);
        throw e;
    }
};
