import api, { route } from '@forge/api';

export const generateReleaseNotes = async (version) => {
    try {
        const jql = "project = KAN AND status = Done ORDER BY updated DESC";
        const res = await api.asApp().requestJira(route`/rest/api/3/search?jql=${jql}&maxResults=5`);
        const data = await res.json();

        const features = data.issues ? data.issues.map(i => `- ${i.key}: ${i.fields.summary}`).join('\n') : "No recent merged features found.";

        const notes = `
      h1. 🚀 Release Notes: ${version}
      
      h2. 📦 Merged Features
      ${features}
      
      h2. 🐛 Bug Fixes
      - Fixed race condition in auth
      - Resolved memory leak in dashboard
      
      _Generated by Rovo Orchestrator_
      `;

        // Create a persistent Jira Issue for these notes
        let issueKey = null;
        let issueLink = null;
        try {
            const createRes = await api.asApp().requestJira(route`/rest/api/3/issue`, {
                method: 'POST',
                headers: { 'Accept': 'application/json', 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    fields: {
                        project: { key: 'KAN' },
                        summary: `🚀 Release Notes: ${version}`,
                        description: {
                            type: 'doc',
                            version: 1,
                            content: [
                                { type: 'paragraph', content: [{ type: 'text', text: `Release Notes for ${version}` }] },
                                { type: 'codeBlock', content: [{ type: 'text', text: notes }] }
                            ]
                        },
                        issuetype: { id: '10001' } // Assuming Task
                    }
                })
            });
            const createData = await createRes.json();
            issueKey = createData.key;
            issueLink = `/browse/${issueKey}`; // Relative link for frontend
        } catch (err) {
            console.error("Failed to save Release Notes to Jira:", err);
        }

        return {
            success: true,
            notes: notes,
            issueKey: issueKey,
            issueLink: issueLink,
            message: `Generated Release Notes for ${version}. Saved as ${issueKey || 'Draft'}.`
        };
    } catch (e) {
        console.error("Release Notes failed:", e);
        throw e;
    }
};
